import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Country&Region",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-background`}>
        <div className="relative flex min-h-screen flex-col bg-background">
          {/* header */}
          <Header />
          {/* main */}
          <div className="flex-1">
            <div >
              {children}
            </div>
          
          </div>
          {/* footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
